---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      provider: lxc
      box: ubuntu-12.04-i386
      box_url: https://dl.dropboxusercontent.com/s/6ogb9ie8kqljhex/vagrant-lxc-precise-i386-2013-09-22.box
      omnibus.chef_version: last
      customize:
        memory: 256M

suites:
  - name: default
    run_list:
      - recipe[webtest::default]
