---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      provider: lxc
      box: fgrehm/trusty64-lxc
      omnibus.chef_version: last
      customize:
        cgroup.memory.limit_in_bytes: 256M

suites:
  - name: default
    run_list:
      - recipe[webtest::default]
